language: php

php:
  - 7.3

sudo: false

addons:
  apt:
    packages:
      - parallel

env:
  - NODE_VERSION="6.0"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install $NODE_VERSION
  - composer self-update
  - composer --version
  - composer install
  - npm install

script:
  # Run full test suite and linting of the code base
  - >
    echo;
    echo "Building assets";
    npm run build:suite
#  - >
#    echo;
#    echo "Running unit tests";
#    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit
  - >
    echo;
    echo "Running PHP Coding Standards Fixer checks";
    .Build/bin/php-cs-fixer fix --config=Build/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $COMMIT_RANGE`