/**
 * Used to load HTML fragment variants generated by fluid
 * @param context the webpack require context used to
 * @param defaultKey the preferred fragment defaultKey
 * @returns {{defaultKey: string, cache: {}}}
 */
export const loadFragments = (context, defaultKey) => {
    const cache = {};

    context.keys()
        .forEach((key) => (cache[key] = context(key)));

    // check if defaultKey exists and reset if not
    if (!cache[defaultKey]) {
        defaultKey = Object.keys(cache)[0];
    }

    return {
        defaultKey,
        cache
    };
};

export default loadFragments;
