services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\FrontendEditing\Middleware\FrontendEditing:
    public: true
    arguments:
      $responseFactory: '@Psr\Http\Message\ResponseFactoryInterface'
      $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'

  TYPO3\CMS\FrontendEditing\:
    resource: '../Classes/*'

  TYPO3\CMS\FrontendEditing\Controller\ReceiverController:
    public: true

  TYPO3\CMS\FrontendEditing\Backend\Controller\ContentElement\NewContentElementController:
    public: true

  TYPO3\CMS\FrontendEditing\Controller\Event\Handler\TypoScriptPrepareFieldUpdateEventHandler:
    tags:
      - name: event.listener
        identifier: typoScriptPrepareFieldUpdate
        event: TYPO3\CMS\FrontendEditing\Controller\Event\PrepareFieldUpdateEvent
